gitlab-runner-shell:
  image: oomathias/gitlab-runner:latest
  volumes:
    - /srv/docker/gitlab-runner/shell:/etc/gitlab-runner
  environment:
    - CI_SERVER_URL=
    - RUNNER_TOKEN=
    - RUNNER_DESCRIPTION=shell
    - RUNNER_TAG_LIST=shell
    - RUNNER_EXECUTOR=shell

gitlab-runner-docker:
  image: oomathias/gitlab-runner:latest
  volumes:
    - /srv/docker/gitlab-runner/docker:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock:ro
  environment:
    - CI_SERVER_URL=
    - RUNNER_TOKEN=
    - RUNNER_DESCRIPTION=docker
    - RUNNER_TAG_LIST=docker
    - RUNNER_EXECUTOR=docker
